### ISSUE TITLE
Any plans for flatpak?

### ISSUE THREAD

**Issue by arandilopez** [smoser/pdftk#8]
Hi @smoser and thank you for this snap. Do you have any plan to also provide a flatpak distribution?

**Comment by smoser** [comment]
I'm willing to take patches.  But i have not done much at all with this snap after first creating it to scratch an itch.

I have not looked much at [pdftk-java](https://gitlab.com/pdftk-java/pdftk) but thought that ultimately that was would be the replacement, since it is currently actively maintained.
